--Remove Databases from AG
Use master;
Go

ALTER DATABASE [BusinessMappings] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [BusinessMappings]
Go

ALTER DATABASE [CDM] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [CDM]
Go

ALTER DATABASE [CWC] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [CWC]
Go

ALTER DATABASE [MDMCustomer] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [MDMCustomer]
Go

ALTER DATABASE [MDMPartner] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [MDMPartner]
Go

ALTER DATABASE [MyCitrixReports] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [MyCitrixReports]
Go

ALTER DATABASE [PartnerSynchDB] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [PartnerSynchDB]
Go

ALTER DATABASE [Playmaker] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [Playmaker]
Go

ALTER DATABASE [POSEnrichment] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [POSEnrichment]
Go

ALTER DATABASE [ReplicaCADS] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [ReplicaCADS]
Go

ALTER DATABASE [ReplicaCallidus] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [ReplicaCallidus]
Go

ALTER DATABASE [ReplicaCRMDB] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [ReplicaCRMDB]
Go

ALTER DATABASE [ReplicaDuns] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [ReplicaDuns]
Go

ALTER DATABASE [ReplicaEmployeeSnapshot] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [ReplicaEmployeeSnapshot]
Go

ALTER DATABASE [ReplicaFNOShell] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [ReplicaFNOShell]
Go

ALTER DATABASE [ReplicaFnpops] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [ReplicaFnpops]
Go

ALTER DATABASE [ReplicaIntegrationData] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [ReplicaIntegrationData]
Go

ALTER DATABASE [ReplicaSDE] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [ReplicaSDE]
Go

ALTER DATABASE [Reports] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [Reports]
Go

ALTER DATABASE [Salesforce] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [Salesforce]
Go

ALTER DATABASE [SAPBI] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [SAPBI]
Go

ALTER DATABASE [SAPORDER] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [SAPORDER]
Go

ALTER DATABASE [UserSynchDB] SET HADR SUSPEND;
GO
Alter AVAILABILITY GROUP [ODS]
REMOVE DATABASE [UserSynchDB]
Go


--Remove Replicas from AG

ALTER AVAILABILITY GROUP [ODS]
REMOVE REPLICA ON FTLPODSSQL03
GO

ALTER AVAILABILITY GROUP [ODS]
REMOVE REPLICA ON FTLPODSSQL04
GO