-- SEARCH FOR OBJECT
-- FIND A TABLE IN ALL DATABASES ON SERVER.
EXEC sp_msforeachdb N'USE [?];
SELECT
@@SERVERNAME + '' | '' + SUSER_SNAME() + '' | ''+ DB_NAME() + '' | '' + CONVERT(VARCHAR(20),getdate(),120) as [SOURCE],
TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME ,
''[''+ CAST(@@SERVERNAME AS VARCHAR(100))+ ''].[''+ TABLE_CATALOG + ''].[''+ TABLE_SCHEMA + ''].[''+ TABLE_NAME + '']'' as [FQN]
FROM [?].INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE ''%sw_inst_product%'';
'
GO